// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2jrx_Xy2WgQpMb-W4ZnG52GvUu9Dfmo',
    appId: '1:303816241992:web:960f27cb60387122e9f97d',
    messagingSenderId: '303816241992',
    projectId: 'bantay-daan',
    authDomain: 'bantay-daan.firebaseapp.com',
    storageBucket: 'bantay-daan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKqiKLTOLE8AOsavx9qBNOyjoqzf6ngTo',
    appId: '1:303816241992:android:595ccede8bed28c4e9f97d',
    messagingSenderId: '303816241992',
    projectId: 'bantay-daan',
    storageBucket: 'bantay-daan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2nXeLjr3bGVisWlcUZI_VqtdfOpJSZQ',
    appId: '1:303816241992:ios:3bc6649d3557f7dbe9f97d',
    messagingSenderId: '303816241992',
    projectId: 'bantay-daan',
    storageBucket: 'bantay-daan.firebasestorage.app',
    iosBundleId: 'com.example.bantayDaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2nXeLjr3bGVisWlcUZI_VqtdfOpJSZQ',
    appId: '1:303816241992:ios:3bc6649d3557f7dbe9f97d',
    messagingSenderId: '303816241992',
    projectId: 'bantay-daan',
    storageBucket: 'bantay-daan.firebasestorage.app',
    iosBundleId: 'com.example.bantayDaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl2jrx_Xy2WgQpMb-W4ZnG52GvUu9Dfmo',
    appId: '1:303816241992:web:fd2d568e74d114d8e9f97d',
    messagingSenderId: '303816241992',
    projectId: 'bantay-daan',
    authDomain: 'bantay-daan.firebaseapp.com',
    storageBucket: 'bantay-daan.firebasestorage.app',
  );
}
